// Generated by scripts/page-dates.mjs. Do not edit.
export type PageDate = {
  published: string;
  modified: string;
  hash: string;
};

export const PAGE_DATES: Record<string, PageDate> = {
  "/AI": {
    "published": "2026-09-28T12:47:11+09:00",
    "modified": "2026-09-28T12:47:11+09:00",
    "hash": "578d9dcebf3e22b9"
  },
  "/admin": {
    "published": "2026-09-14T04:13:18+09:00",
    "modified": "2026-09-14T04:13:18+09:00",
    "hash": "3ca06dfd4a51eff4"
  },
  "/analyze": {
    "published": "2026-08-13T05:02:46+09:00",
    "modified": "2026-08-13T05:02:46+09:00",
    "hash": "db5bf9ef45d516b6"
  },
  "/auth/accept": {
    "published": "2026-09-07T10:39:11+09:00",
    "modified": "2026-09-07T10:39:11+09:00",
    "hash": "c3cb7942220c23b8"
  },
  "/auth/bridge": {
    "published": "2026-09-07T10:39:11+09:00",
    "modified": "2026-09-07T10:39:11+09:00",
    "hash": "f2ee280123b0e7e0"
  },
  "/c/$soulId": {
    "published": "2026-09-14T04:13:18+09:00",
    "modified": "2026-09-14T04:13:18+09:00",
    "hash": "1d58082fe29609e9"
  },
  "/cloud": {
    "published": "2026-08-13T05:02:46+09:00",
    "modified": "2026-08-13T05:02:46+09:00",
    "hash": "a0628f6814802aad"
  },
  "/effector": {
    "published": "2026-09-18T08:35:31+09:00",
    "modified": "2026-09-18T08:35:31+09:00",
    "hash": "af284b9fc73fbd23"
  },
  "/": {
    "published": "2026-10-04T17:13:35+09:00",
    "modified": "2026-10-04T17:13:35+09:00",
    "hash": "b6b9dce50ceaec92"
  },
  "/login": {
    "published": "2026-09-14T04:13:18+09:00",
    "modified": "2026-09-14T04:13:18+09:00",
    "hash": "f43cf131cf4592d5"
  },
  "/obs": {
    "published": "2026-09-18T09:15:13+09:00",
    "modified": "2026-09-18T09:15:13+09:00",
    "hash": "61caee8ae5affc97"
  },
  "/profile": {
    "published": "2026-09-14T04:13:18+09:00",
    "modified": "2026-09-14T04:13:18+09:00",
    "hash": "282434ee814eed43"
  },
  "/range": {
    "published": "2026-09-18T09:05:35+09:00",
    "modified": "2026-09-18T09:05:35+09:00",
    "hash": "6d3d30efe353e439"
  },
  "/remote/$code": {
    "published": "2026-09-18T11:13:26+09:00",
    "modified": "2026-09-18T11:13:26+09:00",
    "hash": "4c2166d6339d1559"
  },
  "/remote": {
    "published": "2026-09-18T11:18:12+09:00",
    "modified": "2026-09-18T11:18:12+09:00",
    "hash": "a263add4e9397c0a"
  },
  "/songdb/$code": {
    "published": "2026-09-14T04:13:18+09:00",
    "modified": "2026-09-14T04:13:18+09:00",
    "hash": "236d4f2f55c99b4d"
  },
  "/songdb": {
    "published": "2026-09-14T04:13:18+09:00",
    "modified": "2026-09-14T04:13:18+09:00",
    "hash": "d3749e8059890ee2"
  },
  "/terms": {
    "published": "2026-09-09T09:26:52+09:00",
    "modified": "2026-09-09T09:26:52+09:00",
    "hash": "ea4ce4ff49f73072"
  },
  "/train": {
    "published": "2026-10-04T17:13:35+09:00",
    "modified": "2026-10-04T17:13:35+09:00",
    "hash": "795d5a7b27f4252b"
  },
  "/u/$slug": {
    "published": "2026-09-07T10:28:14+09:00",
    "modified": "2026-09-07T10:28:14+09:00",
    "hash": "4c908919baa9c4d9"
  }
};
