/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AIRouteImport } from './routes/AI'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as EffectorRouteImport } from './routes/effector'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ObsRouteImport } from './routes/obs'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RangeRouteImport } from './routes/range'
import { Route as RemoteRouteImport } from './routes/remote'
import { Route as SongdbRouteImport } from './routes/songdb'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAuthPublicConfigRouteImport } from './routes/api/auth-public-config'
import { Route as ApiRemoteRoomRouteImport } from './routes/api/remote-room'
import { Route as AuthAcceptRouteImport } from './routes/auth/accept'
import { Route as AuthBridgeRouteImport } from './routes/auth/bridge'
import { Route as CSoulIdRouteImport } from './routes/c.$soulId'
import { Route as SongdbIndexRouteImport } from './routes/songdb.index'
import { Route as SongdbCodeRouteImport } from './routes/songdb.$code'
import { Route as USlugRouteImport } from './routes/u.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiSoundfontIdRouteImport } from './routes/api/soundfont.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AIRoute = AIRouteImport.update({
  id: '/AI',
  path: '/AI',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectorRoute = EffectorRouteImport.update({
  id: '/effector',
  path: '/effector',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ObsRoute = ObsRouteImport.update({
  id: '/obs',
  path: '/obs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeRoute = RangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteRoute = RemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => rootRouteImport,
} as any)
const SongdbRoute = SongdbRouteImport.update({
  id: '/songdb',
  path: '/songdb',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPublicConfigRoute = ApiAuthPublicConfigRouteImport.update({
  id: '/api/auth-public-config',
  path: '/api/auth-public-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteRoomRoute = ApiRemoteRoomRouteImport.update({
  id: '/api/remote-room',
  path: '/api/remote-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptRoute = AuthAcceptRouteImport.update({
  id: '/auth/accept',
  path: '/auth/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth/bridge',
  path: '/auth/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const CSoulIdRoute = CSoulIdRouteImport.update({
  id: '/c/$soulId',
  path: '/c/$soulId',
  getParentRoute: () => rootRouteImport,
} as any)
const SongdbIndexRoute = SongdbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SongdbRoute,
} as any)
const SongdbCodeRoute = SongdbCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SongdbRoute,
} as any)
const USlugRoute = USlugRouteImport.update({
  id: '/u/$slug',
  path: '/u/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoundfontIdRoute = ApiSoundfontIdRouteImport.update({
  id: '/api/soundfont/$id',
  path: '/api/soundfont/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AI': typeof AIRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/cloud': typeof CloudRoute
  '/effector': typeof EffectorRoute
  '/login': typeof LoginRoute
  '/obs': typeof ObsRoute
  '/profile': typeof ProfileRoute
  '/range': typeof RangeRoute
  '/remote': typeof RemoteRoute
  '/songdb': typeof SongdbRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/auth-public-config': typeof ApiAuthPublicConfigRoute
  '/api/remote-room': typeof ApiRemoteRoomRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/c/$soulId': typeof CSoulIdRoute
  '/songdb/$code': typeof SongdbCodeRoute
  '/u/$slug': typeof USlugRoute
  '/songdb/': typeof SongdbIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/soundfont/$id': typeof ApiSoundfontIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AI': typeof AIRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/cloud': typeof CloudRoute
  '/effector': typeof EffectorRoute
  '/login': typeof LoginRoute
  '/obs': typeof ObsRoute
  '/profile': typeof ProfileRoute
  '/range': typeof RangeRoute
  '/remote': typeof RemoteRoute
  '/terms': typeof TermsRoute
  '/api/auth-public-config': typeof ApiAuthPublicConfigRoute
  '/api/remote-room': typeof ApiRemoteRoomRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/c/$soulId': typeof CSoulIdRoute
  '/songdb/$code': typeof SongdbCodeRoute
  '/u/$slug': typeof USlugRoute
  '/songdb': typeof SongdbIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/soundfont/$id': typeof ApiSoundfontIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AI': typeof AIRoute
  '/admin': typeof AdminRoute
  '/analyze': typeof AnalyzeRoute
  '/cloud': typeof CloudRoute
  '/effector': typeof EffectorRoute
  '/login': typeof LoginRoute
  '/obs': typeof ObsRoute
  '/profile': typeof ProfileRoute
  '/range': typeof RangeRoute
  '/remote': typeof RemoteRoute
  '/songdb': typeof SongdbRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/auth-public-config': typeof ApiAuthPublicConfigRoute
  '/api/remote-room': typeof ApiRemoteRoomRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/c/$soulId': typeof CSoulIdRoute
  '/songdb/$code': typeof SongdbCodeRoute
  '/u/$slug': typeof USlugRoute
  '/songdb/': typeof SongdbIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/soundfont/$id': typeof ApiSoundfontIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AI'
    | '/admin'
    | '/analyze'
    | '/cloud'
    | '/effector'
    | '/login'
    | '/obs'
    | '/profile'
    | '/range'
    | '/remote'
    | '/songdb'
    | '/terms'
    | '/api/auth-public-config'
    | '/api/remote-room'
    | '/auth/accept'
    | '/auth/bridge'
    | '/c/$soulId'
    | '/songdb/$code'
    | '/u/$slug'
    | '/songdb/'
    | '/api/auth/$'
    | '/api/soundfont/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AI'
    | '/admin'
    | '/analyze'
    | '/cloud'
    | '/effector'
    | '/login'
    | '/obs'
    | '/profile'
    | '/range'
    | '/remote'
    | '/terms'
    | '/api/auth-public-config'
    | '/api/remote-room'
    | '/auth/accept'
    | '/auth/bridge'
    | '/c/$soulId'
    | '/songdb/$code'
    | '/u/$slug'
    | '/songdb'
    | '/api/auth/$'
    | '/api/soundfont/$id'
  id:
    | '__root__'
    | '/'
    | '/AI'
    | '/admin'
    | '/analyze'
    | '/cloud'
    | '/effector'
    | '/login'
    | '/obs'
    | '/profile'
    | '/range'
    | '/remote'
    | '/songdb'
    | '/terms'
    | '/api/auth-public-config'
    | '/api/remote-room'
    | '/auth/accept'
    | '/auth/bridge'
    | '/c/$soulId'
    | '/songdb/$code'
    | '/u/$slug'
    | '/songdb/'
    | '/api/auth/$'
    | '/api/soundfont/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AIRoute: typeof AIRoute
  AdminRoute: typeof AdminRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CloudRoute: typeof CloudRoute
  EffectorRoute: typeof EffectorRoute
  LoginRoute: typeof LoginRoute
  ObsRoute: typeof ObsRoute
  ProfileRoute: typeof ProfileRoute
  RangeRoute: typeof RangeRoute
  RemoteRoute: typeof RemoteRoute
  SongdbRoute: typeof SongdbRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiAuthPublicConfigRoute: typeof ApiAuthPublicConfigRoute
  ApiRemoteRoomRoute: typeof ApiRemoteRoomRoute
  AuthAcceptRoute: typeof AuthAcceptRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  CSoulIdRoute: typeof CSoulIdRoute
  USlugRoute: typeof USlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiSoundfontIdRoute: typeof ApiSoundfontIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AI': {
      id: '/AI'
      path: '/AI'
      fullPath: '/AI'
      preLoaderRoute: typeof AIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effector': {
      id: '/effector'
      path: '/effector'
      fullPath: '/effector'
      preLoaderRoute: typeof EffectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obs': {
      id: '/obs'
      path: '/obs'
      fullPath: '/obs'
      preLoaderRoute: typeof ObsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range': {
      id: '/range'
      path: '/range'
      fullPath: '/range'
      preLoaderRoute: typeof RangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote': {
      id: '/remote'
      path: '/remote'
      fullPath: '/remote'
      preLoaderRoute: typeof RemoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songdb': {
      id: '/songdb'
      path: '/songdb'
      fullPath: '/songdb'
      preLoaderRoute: typeof SongdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-public-config': {
      id: '/api/auth-public-config'
      path: '/api/auth-public-config'
      fullPath: '/api/auth-public-config'
      preLoaderRoute: typeof ApiAuthPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/remote-room': {
      id: '/api/remote-room'
      path: '/api/remote-room'
      fullPath: '/api/remote-room'
      preLoaderRoute: typeof ApiRemoteRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept': {
      id: '/auth/accept'
      path: '/auth/accept'
      fullPath: '/auth/accept'
      preLoaderRoute: typeof AuthAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bridge': {
      id: '/auth/bridge'
      path: '/auth/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$soulId': {
      id: '/c/$soulId'
      path: '/c/$soulId'
      fullPath: '/c/$soulId'
      preLoaderRoute: typeof CSoulIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songdb/': {
      id: '/songdb/'
      path: '/'
      fullPath: '/songdb/'
      preLoaderRoute: typeof SongdbIndexRouteImport
      parentRoute: typeof SongdbRoute
    }
    '/songdb/$code': {
      id: '/songdb/$code'
      path: '/$code'
      fullPath: '/songdb/$code'
      preLoaderRoute: typeof SongdbCodeRouteImport
      parentRoute: typeof SongdbRoute
    }
    '/u/$slug': {
      id: '/u/$slug'
      path: '/u/$slug'
      fullPath: '/u/$slug'
      preLoaderRoute: typeof USlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/soundfont/$id': {
      id: '/api/soundfont/$id'
      path: '/api/soundfont/$id'
      fullPath: '/api/soundfont/$id'
      preLoaderRoute: typeof ApiSoundfontIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SongdbRouteChildren {
  SongdbCodeRoute: typeof SongdbCodeRoute
  SongdbIndexRoute: typeof SongdbIndexRoute
}

const SongdbRouteChildren: SongdbRouteChildren = {
  SongdbCodeRoute: SongdbCodeRoute,
  SongdbIndexRoute: SongdbIndexRoute,
}

const SongdbRouteWithChildren =
  SongdbRoute._addFileChildren(SongdbRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AIRoute: AIRoute,
  AdminRoute: AdminRoute,
  AnalyzeRoute: AnalyzeRoute,
  CloudRoute: CloudRoute,
  EffectorRoute: EffectorRoute,
  LoginRoute: LoginRoute,
  ObsRoute: ObsRoute,
  ProfileRoute: ProfileRoute,
  RangeRoute: RangeRoute,
  RemoteRoute: RemoteRoute,
  SongdbRoute: SongdbRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiAuthPublicConfigRoute: ApiAuthPublicConfigRoute,
  ApiRemoteRoomRoute: ApiRemoteRoomRoute,
  AuthAcceptRoute: AuthAcceptRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  CSoulIdRoute: CSoulIdRoute,
  USlugRoute: USlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSoundfontIdRoute: ApiSoundfontIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
