/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as EffectorRouteImport } from './routes/effector'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RangeRouteImport } from './routes/range'
import { Route as ApiAuthPublicConfigRouteImport } from './routes/api/auth-public-config'
import { Route as AuthAcceptRouteImport } from './routes/auth/accept'
import { Route as AuthBridgeRouteImport } from './routes/auth/bridge'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const EffectorRoute = EffectorRouteImport.update({
  id: '/effector',
  path: '/effector',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RangeRoute = RangeRouteImport.update({
  id: '/range',
  path: '/range',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthPublicConfigRoute = ApiAuthPublicConfigRouteImport.update({
  id: '/api/auth-public-config',
  path: '/api/auth-public-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptRoute = AuthAcceptRouteImport.update({
  id: '/auth/accept',
  path: '/auth/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth/bridge',
  path: '/auth/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/cloud': typeof CloudRoute
  '/effector': typeof EffectorRoute
  '/login': typeof LoginRoute
  '/range': typeof RangeRoute
  '/api/auth-public-config': typeof ApiAuthPublicConfigRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/cloud': typeof CloudRoute
  '/effector': typeof EffectorRoute
  '/login': typeof LoginRoute
  '/range': typeof RangeRoute
  '/api/auth-public-config': typeof ApiAuthPublicConfigRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/cloud': typeof CloudRoute
  '/effector': typeof EffectorRoute
  '/login': typeof LoginRoute
  '/range': typeof RangeRoute
  '/api/auth-public-config': typeof ApiAuthPublicConfigRoute
  '/auth/accept': typeof AuthAcceptRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/cloud'
    | '/effector'
    | '/login'
    | '/range'
    | '/api/auth-public-config'
    | '/auth/accept'
    | '/auth/bridge'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/cloud'
    | '/effector'
    | '/login'
    | '/range'
    | '/api/auth-public-config'
    | '/auth/accept'
    | '/auth/bridge'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/cloud'
    | '/effector'
    | '/login'
    | '/range'
    | '/api/auth-public-config'
    | '/auth/accept'
    | '/auth/bridge'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  CloudRoute: typeof CloudRoute
  EffectorRoute: typeof EffectorRoute
  LoginRoute: typeof LoginRoute
  RangeRoute: typeof RangeRoute
  ApiAuthPublicConfigRoute: typeof ApiAuthPublicConfigRoute
  AuthAcceptRoute: typeof AuthAcceptRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/effector': {
      id: '/effector'
      path: '/effector'
      fullPath: '/effector'
      preLoaderRoute: typeof EffectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/range': {
      id: '/range'
      path: '/range'
      fullPath: '/range'
      preLoaderRoute: typeof RangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth-public-config': {
      id: '/api/auth-public-config'
      path: '/api/auth-public-config'
      fullPath: '/api/auth-public-config'
      preLoaderRoute: typeof ApiAuthPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept': {
      id: '/auth/accept'
      path: '/auth/accept'
      fullPath: '/auth/accept'
      preLoaderRoute: typeof AuthAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bridge': {
      id: '/auth/bridge'
      path: '/auth/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  CloudRoute: CloudRoute,
  EffectorRoute: EffectorRoute,
  LoginRoute: LoginRoute,
  RangeRoute: RangeRoute,
  ApiAuthPublicConfigRoute: ApiAuthPublicConfigRoute,
  AuthAcceptRoute: AuthAcceptRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
